nome = str(input('Seu nome completo: ')).strip()
print(f'Seu nome em maíusculas é: {nome.upper()}.')
print(f'Seu nome em minúsculas é: {nome.lower()}.')
print(f'Seu nome tem {len(nome) - nome.count(" ")}.')
print(f'Seu primeiro nome tem {nome.find(" ")} letras.')