nome = str(input('Digite seu nome completo: ')).strip()
fat = nome.split()
print('Prazer em te conhecer!')
print('Seu primeiro nome é {}'.format(fat[0]))
print('Seu último nome é {}'.format(fat[len(fat)-1]))
